"""Initial migration

Revision ID: 9957cb9cc528
Revises: 
Create Date: 2025-12-22 22:11:25.657324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9957cb9cc528'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('salary_range', sa.String(length=100), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=True),
    sa.Column('remote', sa.Boolean(), nullable=True),
    sa.Column('skill_match_score', sa.Float(), nullable=True),
    sa.Column('experience_match_score', sa.Float(), nullable=True),
    sa.Column('overall_match_score', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_index('idx_overall_match_active', 'job_listings', ['overall_match_score', 'is_active'], unique=False)
    op.create_index('idx_source_source_id', 'job_listings', ['source', 'source_id'], unique=False)
    op.create_index(op.f('ix_job_listings_company'), 'job_listings', ['company'], unique=False)
    op.create_index(op.f('ix_job_listings_id'), 'job_listings', ['id'], unique=False)
    op.create_index(op.f('ix_job_listings_is_active'), 'job_listings', ['is_active'], unique=False)
    op.create_index(op.f('ix_job_listings_location'), 'job_listings', ['location'], unique=False)
    op.create_index(op.f('ix_job_listings_overall_match_score'), 'job_listings', ['overall_match_score'], unique=False)
    op.create_index(op.f('ix_job_listings_skill_match_score'), 'job_listings', ['skill_match_score'], unique=False)
    op.create_index(op.f('ix_job_listings_source'), 'job_listings', ['source'], unique=False)
    op.create_index(op.f('ix_job_listings_title'), 'job_listings', ['title'], unique=False)
    op.create_table('skill_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('proficiency_level', sa.Integer(), nullable=False),
    sa.Column('experience_years', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category_proficiency', 'skill_profiles', ['category', 'proficiency_level'], unique=False)
    op.create_index(op.f('ix_skill_profiles_category'), 'skill_profiles', ['category'], unique=False)
    op.create_index(op.f('ix_skill_profiles_id'), 'skill_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_skill_profiles_skill_name'), 'skill_profiles', ['skill_name'], unique=True)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_listing_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_followup', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_followup', sa.DateTime(timezone=True), nullable=True),
    sa.Column('followup_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_listing_id'], ['job_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_status_created', 'applications', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_applications_job_listing_id'), 'applications', ['job_listing_id'], unique=False)
    op.create_index(op.f('ix_applications_next_followup'), 'applications', ['next_followup'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_next_followup'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_listing_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_index('idx_status_created', table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_skill_profiles_skill_name'), table_name='skill_profiles')
    op.drop_index(op.f('ix_skill_profiles_id'), table_name='skill_profiles')
    op.drop_index(op.f('ix_skill_profiles_category'), table_name='skill_profiles')
    op.drop_index('idx_category_proficiency', table_name='skill_profiles')
    op.drop_table('skill_profiles')
    op.drop_index(op.f('ix_job_listings_title'), table_name='job_listings')
    op.drop_index(op.f('ix_job_listings_source'), table_name='job_listings')
    op.drop_index(op.f('ix_job_listings_skill_match_score'), table_name='job_listings')
    op.drop_index(op.f('ix_job_listings_overall_match_score'), table_name='job_listings')
    op.drop_index(op.f('ix_job_listings_location'), table_name='job_listings')
    op.drop_index(op.f('ix_job_listings_is_active'), table_name='job_listings')
    op.drop_index(op.f('ix_job_listings_id'), table_name='job_listings')
    op.drop_index(op.f('ix_job_listings_company'), table_name='job_listings')
    op.drop_index('idx_source_source_id', table_name='job_listings')
    op.drop_index('idx_overall_match_active', table_name='job_listings')
    op.drop_table('job_listings')
    # ### end Alembic commands ###

