"""Add agent tasks and locks tables

Revision ID: f700f0214da4
Revises: 9957cb9cc528
Create Date: 2025-12-23 11:40:49.523640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f700f0214da4'
down_revision = '9957cb9cc528'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_tasks',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('assigned_agent', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_tasks_agent_type', 'agent_tasks', ['agent_type'], unique=False)
    op.create_index('idx_agent_tasks_priority', 'agent_tasks', ['priority'], unique=False)
    op.create_index('idx_agent_tasks_status', 'agent_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_agent_tasks_agent_type'), 'agent_tasks', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_tasks_id'), 'agent_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_priority'), 'agent_tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_agent_tasks_status'), 'agent_tasks', ['status'], unique=False)
    op.create_table('agent_locks',
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_token', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ),
    sa.PrimaryKeyConstraint('task_id'),
    sa.UniqueConstraint('lock_token')
    )
    op.create_index('idx_agent_locks_expires', 'agent_locks', ['expires_at'], unique=False)
    op.create_index(op.f('ix_agent_locks_expires_at'), 'agent_locks', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_locks_expires_at'), table_name='agent_locks')
    op.drop_index('idx_agent_locks_expires', table_name='agent_locks')
    op.drop_table('agent_locks')
    op.drop_index(op.f('ix_agent_tasks_status'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_priority'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_agent_type'), table_name='agent_tasks')
    op.drop_index('idx_agent_tasks_status', table_name='agent_tasks')
    op.drop_index('idx_agent_tasks_priority', table_name='agent_tasks')
    op.drop_index('idx_agent_tasks_agent_type', table_name='agent_tasks')
    op.drop_table('agent_tasks')
    # ### end Alembic commands ###

