# PURPOSE: Regenerate PLANS_INDEX.md from plan file frontmatter
# DEPENDENCIES: None
# MODIFICATION NOTES: Criticism remediation; plan file management

$ErrorActionPreference = "Stop"
$PlansDir = Join-Path $PSScriptRoot "..\plans"
$IndexFile = Join-Path $PlansDir "PLANS_INDEX.md"

$plans = Get-ChildItem -Path $PlansDir -Filter "*.plan.md" -ErrorAction SilentlyContinue
if (-not $plans) {
    Write-Host "No plan files found in $PlansDir"
    exit 0
}

$rows = @()
foreach ($f in $plans) {
    $content = Get-Content $f.FullName -Raw
    $name = $f.BaseName
    $path = $f.Name
    $status = "pending"
    $priority = 5
    $phase = "later"
    $resolvedAt = ""

    if ($content -match '(?s)^---\r?\n(.*?)\r?\n---') {
        $front = $Matches[1]
        if ($front -match 'status:\s*(\S+)') { $status = $Matches[1].Trim() }
        if ($front -match 'priority:\s*(\d+)') { $priority = [int]$Matches[1] }
        if ($front -match 'phase:\s*(\S+)') { $phase = $Matches[1].Trim() }
        if ($front -match 'resolved_at:\s*["'']?([^"''\s]+)') { $resolvedAt = $Matches[1] }
        if ($front -match 'name:\s*(.+)') { $name = $Matches[1].Trim().Trim('"') }
    }

    $badge = if ($status -eq "resolved") { " [resolved]" } else { "" }
    $rows += [PSCustomObject]@{
        Name = $name + $badge
        Status = $status
        Priority = $priority
        Phase = $phase
        Path = $path
    }
}

$rows = $rows | Sort-Object { $_.Priority }, { $_.Phase }, { $_.Name }

$md = @()
$md += "# Plans Index"
$md += ""
$md += "Generated by update_plans_index.ps1. Run to refresh."
$md += ""
$md += "| Name | Status | Priority | Phase | Path |"
$md += "|------|--------|----------|-------|------|"

foreach ($r in $rows) {
    $md += "| $($r.Name) | $($r.Status) | $($r.Priority) | $($r.Phase) | $($r.Path) |"
}

$md += ""
$md += "---"
$md += "Priority: 1 = north star; 5 = lowest. Phase: orient, wire, extend, later."

$md | Set-Content -Path $IndexFile -Encoding UTF8
Write-Host "Wrote $IndexFile"
